export const AI_TEST_CASES = [
  {
    id: 'paris_3_jours_modere',
    label: 'Paris 3 jours modéré',
    goal: 'Tester une génération courte, simple, urbaine, sans contrainte complexe.',
    form: {
      destination: 'Paris',
      start_date: '2026-07-10',
      end_date: '2026-07-12',
      budget: 'modere',
      travelers: 2,
      interests: ['culture', 'gastronomie', 'photo'],
      travel_style: 'essentiels',
      organization_level: 'planning',
      walking_level: 'moyen',
      arrival_city: 'Paris',
      return_city: 'Paris',
      arrival_time: '12:00',
      departure_time: '15:00',
      avoid_items: '',
    },
    expected: [
      'itinerary contient exactement 3 jours',
      'tous les jours restent à Paris',
      'jour 1 respecte une arrivée à 12:00',
      'jour 3 respecte un départ à 15:00',
      'aucun dîner complet le jour 3',
      'activités concrètes, pas seulement “visite du centre”',
      'coordonnées GPS présentes pour chaque jour et chaque activité',
      'budget cohérent avec un niveau modéré',
    ],
  },
  {
    id: 'danemark_8_jours_retour_copenhague',
    label: 'Danemark 8 jours avec retour Copenhague',
    goal: 'Tester la logique multi-villes, les transports et le retour explicite.',
    form: {
      destination: 'Danemark',
      start_date: '2026-08-01',
      end_date: '2026-08-08',
      budget: 'modere',
      travelers: 2,
      interests: ['culture', 'nature', 'gastronomie', 'photo'],
      travel_style: 'essentiels',
      organization_level: 'planning',
      walking_level: 'moyen',
      arrival_city: 'Copenhague',
      return_city: 'Copenhague',
      arrival_time: '10:30',
      departure_time: '16:00',
      avoid_items: 'voiture',
    },
    expected: [
      'itinerary contient exactement 8 jours',
      'route géographique logique',
      'nuits groupées par ville',
      'retour final à Copenhague respecté',
      'pas de voiture proposée',
      'transports uniquement quand la ville change',
      'transports crédibles : train, bus, ferry si pertinent',
      'coordonnées GPS plausibles pour toutes les villes et activités',
    ],
  },
  {
    id: 'italie_economique_contraintes',
    label: 'Italie économique avec contraintes',
    goal: 'Tester budget bas + contraintes fortes + cohérence multi-villes.',
    form: {
      destination: 'Italie',
      start_date: '2026-09-05',
      end_date: '2026-09-11',
      budget: 'economique',
      travelers: 2,
      interests: ['culture', 'gastronomie', 'histoire'],
      travel_style: 'immersion',
      organization_level: 'planning',
      walking_level: 'faible',
      arrival_city: 'Rome',
      return_city: 'Venise',
      arrival_time: '14:00',
      departure_time: '11:00',
      avoid_items: 'restaurants chers, longues marches, lieux trop touristiques',
    },
    expected: [
      'itinerary contient exactement 7 jours',
      'Rome / Florence / Venise dans un ordre logique',
      'budget économique visible dans les choix',
      'restaurants simples, marchés, adresses locales',
      'marche faible respectée : activités accessibles via transports/taxi',
      'moins d’ultra-incontournables touristiques',
      'pas de dîner le jour du départ',
      'coordonnées GPS présentes',
    ],
  },
];

export const AI_TEST_CRITERIA = [
  {
    id: 'json_strict',
    label: 'JSON strict',
    check: 'La réponse est un objet JSON parsable, sans markdown.',
  },
  {
    id: 'exact_days',
    label: 'Nombre exact de jours',
    check: 'itinerary.length correspond exactement aux dates / jours demandés.',
  },
  {
    id: 'coords',
    label: 'Coordonnées GPS',
    check: 'Chaque jour et chaque activité possède lat/lng numériques.',
  },
  {
    id: 'constraints',
    label: 'Contraintes respectées',
    check: 'Les éléments à éviter sont réellement visibles dans le résultat.',
  },
  {
    id: 'timing',
    label: 'Horaires réalistes',
    check: 'Premier et dernier jour respectent arrivée/départ.',
  },
  {
    id: 'transport',
    label: 'Transports cohérents',
    check: 'Transport uniquement si changement de ville, mode crédible.',
  },
  {
    id: 'budget',
    label: 'Budget cohérent',
    check: 'Activités, restaurants, transports et hôtels restent cohérents avec le budget.',
  },
  {
    id: 'quality',
    label: 'Qualité voyage',
    check: 'Activités concrètes, pas génériques, pas de tunnel de texte.',
  },
];

export const AI_COMMON_ERROR_LOG_TEMPLATE = [
  'JSON non parsable',
  'Nombre de jours incorrect',
  'Coordonnées GPS manquantes',
  'Dîner ajouté le jour du départ',
  'Transport ajouté alors que la ville ne change pas',
  'Retour ville non respecté',
  'Contraintes “à éviter” ignorées',
  'Activités trop génériques',
  'Budget incohérent',
  'Trop de changements de ville',
];
